# Generated by Django 5.0.6 on 2024-06-20 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollment.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Mentor'), ('S', 'Student')], default='S', max_length=2),
        ),
    ]
