# Generated by Django 5.0.6 on 2024-06-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_profile_role_alter_role_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('NE', 'Not Enrolled'), ('E', 'Enrolled'), ('P', 'Passed'), ('F', 'Failed')], default='E', max_length=3),
        ),
    ]
