# Generated by Django 5.0.6 on 2024-07-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_alter_enrollment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='predmet',
            new_name='subject',
        ),
    ]
