# Generated by Django 5.0.6 on 2024-08-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_rename_predmet_enrollment_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='subject',
            new_name='cousrse',
        ),
    ]
