# Generated by Django 5.0.6 on 2024-08-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_rename_subject_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_elective',
            new_name='is_optional',
        ),
    ]
