# Generated by Django 5.0.6 on 2024-08-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0007_rename_is_elective_course_is_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time')], max_length=2),
        ),
    ]
