# Generated by Django 5.0.6 on 2024-08-15 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0009_alter_profile_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='cousrse',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollment.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Mentor'), ('S', 'Student')], max_length=2),
        ),
    ]
