# Generated by Django 5.0.6 on 2024-08-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0010_rename_cousrse_enrollment_course_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('N', 'None'), ('FT', 'Full-time'), ('PT', 'Part-time')], default='FT', max_length=2),
        ),
    ]
