# Generated by Django 5.0.6 on 2024-08-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0011_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('E', 'Enrolled'), ('P', 'Passed'), ('FR', 'Failed Requirements')], default='E', max_length=3),
        ),
    ]
